# This is a basic workflow to help you get started with Actions

name: Update readme with blog posts

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  schedule:
    # Once a day at 8 AM
    - cron: 0 8 * * *
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://dev.to/feed/alexandergekov
          readme-section: feed
          max: 6 # max number of items (default 5)
          template: "#### [{{ title }}]({{ link }})\n"
